version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    command: ["node", "index.js"]
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    command: ["nginx", '-g', 'daemon off;']
    entrypoint: dockerize -wait tcp://app:3000 -timeout 60s
    networks:
      - node-network
    tty: true
    depends_on:
      - app
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network



networks:
  node-network:
    driver: bridge
